### ISSUE TITLE
Cant start the godot .exe built with this module (Missing GGPO.dll)

### ISSUE THREAD

**Issue by Kronos328** [FlutterTal/godot_ggpo#6]
Hello! I've been trying to build the godot executable with this module. I've managed to build it sucessfully, but when I go to start it, it says the following:

![37fHvOAxqO](https://user-images.githubusercontent.com/37886706/89241744-1e856e00-d5d6-11ea-8db5-51f7a8184e6e.png)

I've tried reinstalling and rebuilding from scratch, but the problem still persists

**Comment by FlutterTal** [comment]
While building GGPO, did you tell CMake to build the library as a shared library? You need to do that in order to have the .dll file.
Then once you did it, you simply have to put the dll in the same folder as your godot executable. In fact, it's the same thing you have to do if you wanna implement a module to godot that use a library.

**Comment by Kronos328** [comment]
I'll try that, thank you very much!

**Comment by FlutterTal** [comment]
No probs! Might as well close the issue
